### ISSUE TITLE
Does not work with 4Dv16.3 and macOS 10.12.3

### ISSUE THREAD

**Issue by Bernd-HAL** [miyako/4d-plugin-dock-tile#1]
DOCK GET SCREEN FRAME ($l_x;$l_y;$l_width;$l_height)

$l_height does not change if the Dock is visible/invisible or if  the visible Dock is resized.

**Comment by miyako** [comment]
the [current impl](https://github.com/miyako/4d-plugin-dock-tile/blob/master/Dock%20Tile/4DPlugin.cpp) is

```obj-c
NSScreen *mainScreen = [NSScreen mainScreen];
NSRect rect = [mainScreen visibleFrame];
```

maybe you know of a better way?
