### ISSUE TITLE
DOCK Bounce Error in 4D v16R5 64-bit

### ISSUE THREAD

**Issue by jeffgrann** [miyako/4d-plugin-dock-tile#2]
When running in 4D v16R5 64-bit on Mac OS X 10.13.3, an error occurs when executing DOCK Bounce.  Works okay in 32-bit.  Does this plugin need to be updated for 64-bit?

<img width="642" alt="screen shot 2018-03-11 at 6 04 09 pm" src="https://user-images.githubusercontent.com/2565267/37259020-21ab84a2-2557-11e8-99d2-3b4993a269c5.png">

**Comment by miyako** [comment]
it sounds like you are using the version inside the v11 folder. 
you might want to replace it with the one inside the top-level folder.

**Comment by jeffgrann** [comment]
That was it. Thanks Miyako!
