### ISSUE TITLE
DOCK tile / notarization

### ISSUE THREAD

**Issue by ldechamps** [miyako/4d-plugin-dock-tile#4]
We use you're plugin with our 17R6 version's application, and since February 3, we've got 10.9 sdk trouble with the notarization. Do you know how we can pass this problem. Regards.

**Comment by miyako** [comment]
I've posted a couple of releases;
can you please share which, if any, works for you?

https://github.com/miyako/4d-plugin-dock-tile/releases/tag/2.0.v17
https://github.com/miyako/4d-plugin-dock-tile/releases/tag/2.0.v18

the difference between v17 and v18 is the location of ``manifest.json``
v18 has it inside ``Resources``.

both builds were successfully notarised today but v17 may fail depending on how you sign your app

[v18](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma123/v4/24/8c/ff/248cff3f-fe13-46a9-2f8f-a5c1887f10c0/developer_log.json?accessKey=1581150233_2602312111636697122_x9cy3hD2FPFqLaMcgQrwMvjWaoRZFTVxP3P2C%2F3a1MCTANWZEx2iHLPJ%2B%2FcQo%2BFq8WFeQ8TMT1wK%2BsHw8HnFCqe697A1zMoQB5ZMVW35q0ZYWFekp62GtRKZa6myWD%2B5kpUjJwi1Uviu7YTpb01gXQwSekTz6MC2wBi1a1Qp%2B%2FA%3D)

[v17](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma123/v4/60/bd/2b/60bd2b08-8f68-7544-4261-2a7a67bc5d7c/developer_log.json?accessKey=1581150257_8533479112843794661_I1wUtw6uKcyCuEIQheJQujQRoSdfF029mGyuoHtCReEfL5laSd4AycL32q2p1Kbh3algutisE57645l%2BlKkLAy%2FqfKqr7wRHKUmIMp1sGb186aaA5rIx8ic9a7PYX6u0DKaTGvkCO%2B%2BEMdNi5Rn74Xo8HN09MYd2xy%2FWfH4WGzg%3D)

**Comment by ldechamps** [comment]
Thks, that's work with v17R6. Next time we go to try the v18 version.
For the manifest.json file we use "find" function to search it, so no problem with the location.
Do you have some plan for "PDF Kit" Plugin because we use the Pdf Count Page function ?
Thks

**Comment by miyako** [comment]
I can upgrade for reference, but the original plugin had a lot of bugs and patches (for El Capitan) I am not going to test it thoroughly. you should use it with caution.
