### ISSUE TITLE
Dock_Bounce_Indefinite missing?

### ISSUE THREAD

**Issue by jeffgrann** [miyako/4d-plugin-dock-tile#5]
After upgrading to the latest version of this plugin with 4D v18, I'm now getting a syntax error stating, "This value cannot be passed as a parameter to this command or method" for the call: $Result:=DOCK Bounce (Dock_Bounce_Indefinite).

**Comment by miyako** [comment]
in other words, constants are not tokenised

<img width="419" alt="Screen Shot 2020-02-22 at 6 10 14" src="https://user-images.githubusercontent.com/1725068/75072074-1232ba80-553a-11ea-9719-dd793c87449f.png">

**Comment by miyako** [comment]
if you can't wait for a fix

Dock_Bounce_One_Second=10
Dock_Bounce_Indefinite=1

**Comment by miyako** [comment]
fixed in release 2.1
